services:
  postgrespg:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=sathishaipg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5463:5432
