services:
  postgrespg:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=sathishaipg
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5463:5432
  postgres:
    image: postgres:18.0
    environment:
      - POSTGRES_DB=sathishai
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=P4ssword!
    ports:
      - 5473:5432
